### ISSUE TITLE
Unable to find type code information for ...

### ISSUE THREAD

**Issue by tmayoff** [OpenDDS/opendds-monitor#31]
I can't seem to get any of my topics types to show. All I get is the above in the log

This is how I'm generating the idl's

```
opendds_idl -Lc++11 -Cw -Gxtypes-complete -o /home/tyler/src/module-GC/build/utils/IDL -I../utils/IDL -I/home/tyler/src/module-GC/utils/IDL ../utils/IDL/Interpreter.idl
```
```
tao_idl -Cw --idl-version 4 --unknown-annotations ignore -GA -GX -o /home/tyler/src/module-GC/build/utils/IDL -I/usr/include -I../utils/IDL -I/home/tyler/src/module-GC/utils/IDL /home/tyler/src/module-GC/build/utils/IDL/InterpreterTypeSupport.idl
```

**Comment by jrw972** [comment]
Did you enable xtypes in your publisher/subscriber with `UseXTypes=complete`?  https://opendds.readthedocs.io/en/latest-release/devguide/run_time_configuration.html#id6

**Comment by tmayoff** [comment]
I did not, I'll try that and get back to you

**Comment by jrw972** [comment]
Duplicate of https://github.com/OpenDDS/opendds-monitor/issues/41
