### ISSUE TITLE
 following virtual functions are pure within ‘DynamicMetaStruct’:

### ISSUE THREAD

**Issue by muhamadnaufalA** [OpenDDS/opendds-monitor#37]
I have error while build the project with command ```cmake --build .``` and the output error like this

![Screenshot 2024-08-15 151548](https://github.com/user-attachments/assets/ddc42514-4b82-4e80-99c2-4542ce6af181)

How resolve this error?

**Comment by muhamadnaufalA** [comment]
Thank you, based on your advice, the build was finally successful... 😊

But how do I run this opendds monitor project so that the QT UI can be seen?

I apologize if my question is just an easy question. I am really a beginner... 🥲

**Comment by muhamadnaufalA** [comment]
Hiiii thank you for your reply... 😊. Now i can build and use open dds monitor because of you, thank you....

May i ask again? 

How can i get type code information of my topic. In open dds monitor will appears error like this : 
![image](https://github.com/user-attachments/assets/b4237b81-4273-409b-9888-fb51449c4024)

And in topic page will not return any data like this 
![image](https://github.com/user-attachments/assets/90045f35-b8a7-4f95-93d2-3b6d2cc7d342)


How to resolve this?

Sorry if my question is an easy question.

**Comment by mitza-oci** [comment]
https://github.com/OpenDDS/opendds-monitor/issues/31

**Comment by muhamadnaufalA** [comment]
okay, i have followed the steps but still get this error. 

```WARNING: get_dynamic_type for topic topics_msg returned No data```

how to solve this warning?

**Comment by mitza-oci** [comment]
This was answered in #31 as far as I know.  If it wasn't actually answered in #31 please create a new issue since it's not related to #37
