### ISSUE TITLE
'Unable to find type code information for...' but topics and values are all showing up & plot & recorder only show "NULL"

### ISSUE THREAD

**Issue by pyphais** [OpenDDS/opendds-monitor#41]
The program log tells me for every topic I open "Unable to find type code information for ___", but unlike previous similar issues I AM getting all of the data from the topic in the window:
![image](https://github.com/user-attachments/assets/4b007a25-3323-45d5-8e4e-de66f70c1e5f)
However, both recording and plotting shows the values of every field to be NULL:
![image](https://github.com/user-attachments/assets/506ff1d5-d7aa-4530-aaa6-03faf1953c15)

The main error I get consistently in the log is just the 'Unable to find type code information for' error, but I also get "Failed to create topic ___" errors as well for some topics. I'm assuming after searching through code that all of these errors likely have to do with not finding the type code information, but I don't understand why it's not able to find it? I need to be able to record samples.

I've compiled all IDLs with `-Gxtypes-complete` using MPC as below:
![image](https://github.com/user-attachments/assets/d95645ff-92bf-4024-afda-bcf1cc99c701)

I've also enabled the use of xtypes with UseXTypes=complete in the opendds.ini file(s). 

I can't seem to figure out why all of the features seem to work except for these couple things. Looking through the code and adding some debugging outputs it seems like the messages being taken in the publication monitor just don't have any user_data/sampleData.topic_data.value, which might cause type code to not exists, which could then cause issues for the recorder since it seems to use typecode somehow, I'm not sure if any of that is related though?

For reference I'm using OpenDDS 3.28.1, and due to this I had to build opendds-monitor from this commit (https://github.com/OpenDDS/opendds-monitor/commit/65c922e1df393ea83bc6481e7a035afd45375038) as the next one (https://github.com/OpenDDS/opendds-monitor/pull/35) required dependencies from OpenDDS 3.29.0. (I can't control the version we're using).

Hopefully I'm just missing a step somewhere and this is a simple fix - any help is appreciated.

**Comment by pyphais** [comment]
I see, thank you, in that case I don't care much about the error and only care about the NULL data. It looks like when I open the plot and it tried to run CommonData::readValue in RecorderDialog::dumpData, sampleList.count() is equal to zero, which sets the values to "NULL":

```
QVariant CommonData::readValue(const QString& topicName,
                               const QString& memberName,
                               const unsigned int& index)
{
    QVariant value;
    QMutexLocker locker(&m_sampleMutex);


    // Make sure the index is valid
    QList<std::shared_ptr<OpenDynamicData>>& sampleList = m_samples[topicName];
    if ((int)index >= sampleList.count())
    {
        value = "NULL";
        std::cout << "sampleList.count(): " << sampleList.count() << std::endl; //my added debugging
        return value;
    }
```

It looks like that's only possible if the sample doesn't get stored properly in m_samples in `CommonData::storeSample` (I don't see m_samples getting populated anywhere else, but I may have missed it). I tried putting debug outputs in that function and it looks like it's never running. Seemingly the only place it gets called is at the end of `TopicMonitor::on_sample_data_received`, but that doesn't seem to be running either. I can't find when that one is supposed to run though... Not sure what I'm missing trying to track this issue down, or if I'm chasing ghosts.

**Comment by pyphais** [comment]
If I'm understanding correctly, it looks like the samples are getting saved to m_dynamicSamples instead of m_samples, but CommonData::readValue (which the recorder runs in RecorderDialog::dumpData() & the plotter runs in GraphPage::updateGraph()) only reads from m_samples? Is this intended or am I missing something?

**Comment by mitza-oci** [comment]
I don't think you're missing anything.  What you found so leads me to believe that some of these features haven't yet been migrated to using the new XTypes dynamic API.  @simpsont-oci @sonndinh or @iguessthislldo may have more info on this.

**Comment by sonndinh** [comment]
> If I'm understanding correctly, it looks like the samples are getting saved to m_dynamicSamples instead of m_samples, but CommonData::readValue (which the recorder runs in RecorderDialog::dumpData() & the plotter runs in GraphPage::updateGraph()) only reads from m_samples? Is this intended or am I missing something?

I think what you've found and what Adam recapped is correct. `CommonData::m_samples` stores samples written using a custom method with CORBA TypeCode before OpenDDS has XTypes dynamic API. With XTypes dynamic API enabled as you showed in your application, `CommonData::m_samples` is not going to be populated; instead, `CommonData::m_dynamicSamples` is populated. However, `CommonData::readValue` is reading data only from `CommonData::m_samples` and the data is not there.

This happens because we haven't fully switched to using the XTypes dynamic data yet. So this is an area that can be improved.

**Comment by sonndinh** [comment]
I'm working on PR #43 to fix this.
